name: Check IP Blocklist File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-ip-filter:
    name: Validate ip-filter.blf File
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Prüfen, ob die Datei existiert
      - name: Check if ip-filter.blf exists
        run: |
          if [ ! -f "ip-filter.blf" ]; then
            echo "Fehler: ip-filter.blf Datei existiert nicht!"
            exit 1
          fi

      # Prüfen, ob die Datei HTML-Code enthält
      - name: Validate ip-filter.blf does not contain HTML
        run: |
          if grep -q "<html" ip-filter.blf; then
            echo "Fehler: Die Datei ip-filter.blf enthält HTML-Code!"
            exit 1
          else
            echo "ip-filter.blf ist gültig."
          fi

      # Optional: Dateiinhalt validieren (Format der IP-Adressen prüfen)
      - name: Validate IP Address Format
        run: |
          if grep -E -v "^(#|[0-9]{1,3}(\.[0-9]{1,3}){3}(/\d{1,2})?)$" ip-filter.blf; then
            echo "Fehler: ip-filter.blf enthält ungültige IP-Adressen oder Kommentare."
            exit 1
          else
            echo "IP-Adressen in ip-filter.blf sind korrekt."
          fi
